name: Publish zop-ui image

on:
  push:
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

jobs:
  prettier-and-lint:
    name: 🧪 Prettier and Lint
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: |
          npm install

      - name: run linter
        run: |
          CI=false npm run lint

      - name: run prettier
        run: |
          CI=false npm run prettier:check

      - name: Build
        run: npm run build

  publich-image:
    if: ${{ startsWith(github.ref, 'refs/tags/v')}}
    name: 🔨 Build and 🐳 Dockerize
    needs: prettier-and-lint
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract Release Tag
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: 'v4vikash'
          password: ${{ secrets.DOCKER_HUB_PAT }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          context: .
          file: Dockerfile
          tags: zopdev/zop-api:${{ env.RELEASE_VERSION }}
